<a href="https://colab.research.google.com/github/Ays230/MachineLearning/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a1=np.array([1,2,4])
a1

array([1, 2, 4])

In [ ]:
a1[1:3]

array([2., 4.])

In [ ]:
a1[-2:]

array([8., 9.])

In [ ]:
a1.ndim  #1,2,3d

1

In [ ]:
a1.shape

(6,)

In [ ]:
a1.dtype

dtype('float64')

In [ ]:
type(a1)

numpy.ndarray

In [ ]:
a1.size

6

In [ ]:
a2=np.array([[1,2,4],[4,5,6],[6,8,7]])
print(a2.ndim,a2.shape,a2.dtype,type(a2),a2.size,sep='\n')

2
(3, 3)
int64
<class 'numpy.ndarray'>
9


In [ ]:
a2

array([[1, 2, 4],
       [4, 5, 6],
       [6, 8, 7]])

In [ ]:
a2[1,2] #1 ci setir,2ci sutun

np.int64(6)

In [ ]:
a2[:,1] # butun setirler,2ci sutun

array([2, 5, 8])

In [ ]:
a2[2]

array([6, 8, 7])

In [ ]:
a2

array([[1, 2, 4],
       [4, 5, 6],
       [6, 8, 7]])

In [ ]:
a2[1:3,2] # 1,2cu setirler, 2cu sutun

array([6, 7])

In [ ]:
a2[1:,0:2]

array([[4, 5],
       [6, 8]])

In [ ]:
a2[a2>5]

array([6, 6, 8, 7])

In [ ]:
a3=np.array([[[1,2,3],[3,4,6],[4,0,7]],
            [[2,4,7],[4,8,9],[2,6,7]]])

In [ ]:
a3

array([[[1, 2, 3],
        [3, 4, 6],
        [4, 0, 7]],

       [[2, 4, 7],
        [4, 8, 9],
        [2, 6, 7]]])

In [ ]:
a3.shape #shape(bloklar,setir,sutun)

(2, 3, 3)

In [ ]:
a3.ndim #3 d array

3

In [ ]:
a3.size

18

In [ ]:
type(a3)

numpy.ndarray

In [ ]:
a3.dtype

dtype('int64')

In [ ]:
a3

array([[[1, 2, 3],
        [3, 4, 6],
        [4, 0, 7]],

       [[2, 4, 7],
        [4, 8, 9],
        [2, 6, 7]]])

In [ ]:
a3[1,1:,1]

array([8, 6])

In [ ]:
a3[1,0:2,1:]

array([[4, 7],
       [8, 9]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
b=np.arange(0,10) #arange(star,stop,step)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.linspace(0,10,6) #0-dan 10na qeder 6 hisseye bol

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [ ]:
np.random.seed(3)
random_arr=np.random.randint(1,10,size=(5,3))
random_arr

array([[9, 4, 9],
       [9, 1, 6],
       [4, 6, 8],
       [7, 1, 5],
       [8, 9, 2]])

In [ ]:
random_arr[1:4,1]

array([1, 6, 1])

In [ ]:
random_arr[1:4,1:2]

array([[1],
       [6],
       [1]])

In [ ]:
random_arr.reshape(3,5)

array([[9, 4, 9, 9, 1],
       [6, 4, 6, 8, 7],
       [1, 5, 8, 9, 2]])

In [ ]:
random_arr.T

array([[9, 9, 4, 7, 8],
       [4, 1, 6, 1, 9],
       [9, 6, 8, 5, 2]])

In [ ]:
np.random.seed(3)
random_arr=np.random.randint(1,10,size=(2,5,3))
random_arr

array([[[9, 4, 9],
        [9, 1, 6],
        [4, 6, 8],
        [7, 1, 5],
        [8, 9, 2]],

       [[7, 3, 3],
        [2, 4, 6],
        [9, 2, 9],
        [8, 9, 2],
        [1, 6, 5]]])

In [ ]:
random_arr[:,3:,1:2]

array([[[1],
        [9]],

       [[9],
        [6]]])

In [ ]:
a1

array([1., 2., 4., 6., 8., 9.])

In [ ]:
a1*2

array([ 2.,  4.,  8., 12., 16., 18.])

In [ ]:
a2

array([[1, 2, 4],
       [4, 5, 6],
       [6, 8, 7]])

In [ ]:
a2.T

array([[1, 4, 6],
       [2, 5, 8],
       [4, 6, 7]])

In [ ]:
a2=np.array([[1,2,3],
            [4,5,6]])

In [ ]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a2.shape,a2.T.shape

((2, 3), (3, 2))

In [ ]:
np.dot(a2,a2.T)

array([[14, 32],
       [32, 77]])

In [ ]:
a2@a2.T

array([[14, 32],
       [32, 77]])

In [ ]:
np.matmul(a2,a2.T)

array([[14, 32],
       [32, 77]])

In [ ]:
a2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
import time
start=time.time()

arr = np.random.randint(1, 10, size = (10000000))**100

end=time.time()

end-start

0.34099364280700684

In [ ]:
import time
start=time.time()
result=[]
for i in range(10000000):
  result.append(i**100)
end=time.time()
end-start



33.03987097740173

In [ ]:
33.03987097740173/0.34099364280700684

96.89292359066472

In [ ]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.sum(a2)

np.int64(21)

In [ ]:
a2.sum()

np.int64(21)

In [ ]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a1

array([1., 2., 4., 6., 8., 9.])

In [ ]:
a2+2

array([[3, 4, 5],
       [6, 7, 8]])

In [ ]:
a1.shape

(3,)

In [ ]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a1

array([1, 2, 4])

In [ ]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a1+a2

array([[ 2,  4,  7],
       [ 5,  7, 10]])